package org.edgo.audio.measure.generator;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Random;

import org.edgo.audio.measure.enums.GenSignalForm;
import org.edgo.audio.measure.fft.FftResult;
import org.edgo.audio.measure.fft.HarmonicsCsv;

import lombok.Value;
import lombok.extern.log4j.Log4j2;

/**
 * DDS (Direct Digital Synthesis) signal generator with 9th-order Taylor sine correction.
 *
 * All periodic waveforms (sine, triangle, rectangle) are driven by a 32-bit phase
 * accumulator.  The sine lookup uses a 4096-entry full-wave table plus a 2nd-order
 * Taylor correction on the fractional phase error.  Triangle and rectangle are
 * piecewise-linear in the phase domain, so the DDS formula is already exact and no
 * correction term is needed.  Triangle has an adjustable duty cycle (rise
 * fraction); at the extremes (≈0 or ≈1) it produces sawtooth-like waveforms.
 *
 * Pink noise is generated by the Voss–McCartney algorithm.  The "linear" variant
 * uses a uniformly distributed (flat-amplitude) white-noise source; the regular
 * variant uses a Gaussian source.
 */
@Log4j2
public class SignalGenerator {


    // -------------------------------------------------------------------------
    // DDS sine lookup table (full wave, 4096 entries)
    // -------------------------------------------------------------------------

    private static final int      TABLE_BITS = 12;
    private static final int      TABLE_SIZE = 1 << TABLE_BITS;   // 65536
    private static final double[] SINE_TABLE = new double[TABLE_SIZE];
    private static final double[] COS_TABLE  = new double[TABLE_SIZE];

    static {
        for (int i = 0; i < TABLE_SIZE; i++) {
            double angle = 2.0 * Math.PI * i / TABLE_SIZE;
            SINE_TABLE[i] = Math.sin(angle);
            COS_TABLE[i]  = Math.cos(angle);
        }
    }

    /**
     * Full-scale peak voltage of the DAC path (V).  Mutable so the
     * GUI / a CLI flag can keep it in step with the matching ADC
     * calibration ({@code AudioBackend.adcFsVoltageRms × √2}).
     * Mismatch between the generator's FS and the reader's assumed
     * FS shows up as the file having "wrong" amplitude when opened
     * in a tool calibrated against the ADC scale.
     */
    public static double FS_VOLTAGE = 2.79351;

    // 2π / 2^32 — used to convert fractional accumulator bits to radians
    private static final double TWO_PI_OVER_2_32 = 2.0 * Math.PI / 4294967296.0;

    // -------------------------------------------------------------------------
    // DDS state
    // -------------------------------------------------------------------------

    /** 32-bit phase accumulator stored in a long to avoid sign issues. */
    private long phaseAcc = 0;
    /** Phase increment per sample.  {@code volatile} so the audio thread sees
     *  freq changes pushed via {@link #setFrequency} from the GUI thread
     *  without a tear (a 64-bit volatile read is atomic on 64-bit JVMs). */
    private volatile long phaseInc;
    /** Second 32-bit phase accumulator for the {@link GenSignalForm#DUAL_TONE}
     *  waveform.  Unused by every other form. */
    private long phaseAcc2 = 0;
    /** Second phase increment for the dual-tone waveform.  Live-swappable
     *  via {@link #setDualToneFrequency2}. */
    private volatile long phaseInc2;
    /** Per-tone linear amplitude weights for the dual-tone waveform.
     *  Each weight equals the user's amplitude percentage / 100.
     *  Combined-signal RMS = {@code amplitude · √((w₁² + w₂²) / 2)},
     *  so {@link #amplitude} is re-normalised against the weights
     *  inside {@link #setDualToneAmplitudes} to keep the RMS equal to
     *  whatever Vrms was last set on {@link #setAmplitudeVrms}.  Live-
     *  swappable. */
    private volatile double dualW1 = 0.5;
    private volatile double dualW2 = 0.5;
    /** Last Vrms value passed to {@link #setAmplitudeVrms}, cached so
     *  the dual-tone amplitude-split path can re-derive
     *  {@link #amplitude} when the weights change without losing the
     *  user's chosen RMS target. */
    private volatile double currentVrms = 0.0;

    // -------------------------------------------------------------------------
    // Generator parameters
    // -------------------------------------------------------------------------

    /** Current waveform.  Live-swappable via {@link #setForm(GenSignalForm)}. */
    private volatile GenSignalForm form;
    /** Linear peak amplitude [0..1].  Live-swappable via {@link #setAmplitudeVrms}. */
    private volatile double     amplitude;
    /** Sample rate cached for live frequency / amplitude updates from the GUI. */
    private final    int        sampleRate;
    /** Duty cycle for {@link GenSignalForm#RECTANGLE} as a fraction [0.01, 0.99].  Default 50 %. */
    private volatile double     rectDuty   = 0.5;
    /** Duty cycle for {@link GenSignalForm#TRIANGLE} as a fraction [0.001, 0.999] —
     *  the rise portion of each period.  0.5 = symmetric triangle; values
     *  near 1.0 / 0.0 produce sawtooth / inverted-sawtooth shapes. */
    private volatile double     triDuty    = 0.5;

    // -------------------------------------------------------------------------
    // Pink noise state — Voss–McCartney algorithm (16 octave rows)
    // -------------------------------------------------------------------------

    private static final int PINK_OCTAVES   = 16;
    private final double[]   pinkRows       = new double[PINK_OCTAVES];
    private double           pinkRunningSum = 0.0;
    private long             pinkCounter    = 0;

    private final Random rng = new Random();

    // -------------------------------------------------------------------------
    // Linear sweep state (LINEAR_SWEEP only)
    // -------------------------------------------------------------------------

    /** Sweep period in samples — chirp restarts after this many samples. */
    private int    sweepPeriodSamples;
    /** Sweep start frequency (Hz). */
    private double sweepFreqStart;
    /** Sweep end frequency (Hz). */
    private double sweepFreqEnd;
    /** Sample rate cached for instantaneous-frequency → phase-step conversion. */
    private double sweepSampleRate;
    /** Sample index within the current sweep period. */
    private int    sweepIdx;
    /** Accumulated phase in radians for the sweep. */
    private double sweepPhase;
    /** Loop the sweep continuously (when true, sweepIdx wraps to 0 at the
     *  end of each cycle).  When false, the generator goes silent after
     *  one cycle.  Applies to both LINEAR_SWEEP and LOG_SWEEP. */
    private volatile boolean sweepLoop      = true;
    /** Hann fade-in length in samples — applied at the start of each
     *  sweep cycle.  0 = no fade. */
    private volatile int     fadeInSamples  = 0;
    /** Hann fade-out length in samples — applied at the end of each
     *  sweep cycle.  0 = no fade. */
    private volatile int     fadeOutSamples = 0;

    // -------------------------------------------------------------------------
    // Log-sweep state (LOG_SWEEP only) — Farina-style exponential chirp
    // -------------------------------------------------------------------------

    /** Pre-rendered unit-amplitude (peak 1.0) log-sweep buffer. Reused as the reference X(t) by the analyzer. */
    private float[] logSweepBuffer;
    /** Lead-in silent samples emitted before the sweep begins. */
    private int     logSweepLeadIn;
    /** Total samples emitted since construction (lead-in + sweep + trailing silence). */
    private long    logSweepIdx;

    // -------------------------------------------------------------------------
    // Harmonic compensation state (SINE_COMPENSATED only)
    // -------------------------------------------------------------------------

    /** Per-harmonic (H2..Hn) amplitude ratio relative to fundamental (amplitude_pct / 100). */
    private double[] hAmpRatio;
    /** Harmonic number (2, 3, 4, …) — used to lock harmonic phase to DDS fundamental. */
    private int[]    hNum;
    /** Per-harmonic initial phase offset (radians). */
    private double[] hPhiInit;

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    /**
     * @param form            waveform type
     * @param frequency       output frequency in Hz (ignored for noise types)
     * @param sampleRate      sample rate in Hz
     * @param amplitudeVRms   desired output amplitude in V RMS
     */
    public SignalGenerator(GenSignalForm form, double frequency, int sampleRate, double amplitudeVRms) {
        this.form        = form;
        this.currentVrms = amplitudeVRms;
        this.amplitude   = amplitudeVRms / (FS_VOLTAGE * rawRms(form));
        this.phaseInc    = Math.round(frequency / sampleRate * 4294967296.0);
        this.sampleRate  = sampleRate;
        log.debug("DDS: form={} freq={}Hz rate={}Hz phaseInc={} amplitude={}V RMS",
                form, frequency, sampleRate, phaseInc, amplitudeVRms);
    }

    /**
     * Constructs a {@link GenSignalForm#SINE_COMPENSATED} generator.
     * Loads H2..Hn harmonic corrections from an {@code fft_harmonics_*.csv} file
     * produced by {@link HarmonicsCsv#export}, or an
     * {@code applied_compensation_*.csv} file from the iterative workflow.
     *
     * <p>If the CSV contains generator-parameter metadata (written by
     * {@link Main#exportAppliedCompensationCsv}) with a calibration amplitude
     * different from {@code amplitudeVRms}, the per-harmonic ratios are scaled
     * by {@code csv_amplitude / amplitudeVRms} so the absolute compensation
     * voltage matches the calibrated value.
     *
     * @param frequency        fundamental frequency in Hz
     * @param sampleRate       sample rate in Hz
     * @param amplitudeVRms    desired fundamental amplitude in V RMS
     * @param harmonicsCsvPath path to the harmonics CSV file
     */
    public SignalGenerator(double frequency, int sampleRate, double amplitudeVRms,
                           String harmonicsCsvPath) throws IOException {
        this(GenSignalForm.SINE_COMPENSATED, frequency, sampleRate, amplitudeVRms);
        loadHarmonics(frequency, sampleRate, harmonicsCsvPath);
    }

    /**
     * Constructs a {@link GenSignalForm#SINE_COMPENSATED} generator directly from a
     * {@link FftResult} — no intermediate CSV file is written.
     * Requires coherent averaging ({@code result.coherentAveraging == true}); otherwise
     * phases are unknown and amplitude-only correction is applied with a warning.
     *
     * @param frequency     fundamental frequency in Hz
     * @param sampleRate    sample rate in Hz
     * @param amplitudeVRms desired fundamental amplitude in V RMS
     * @param result        FFT analysis result containing harmonic amplitudes and phases
     */
    public SignalGenerator(double frequency, int sampleRate, double amplitudeVRms,
                           FftResult result) {
        this(GenSignalForm.SINE_COMPENSATED, frequency, sampleRate, amplitudeVRms);
        loadHarmonicsFromResult(frequency, sampleRate, result);
    }

    /**
     * Constructs a {@link GenSignalForm#SINE_COMPENSATED} generator from pre-computed
     * accumulated harmonic corrections (amplitude + phase arrays).
     * Used by the iterative compensation workflow where corrections are aggregated
     * across multiple iterations as complex numbers.
     *
     * @param frequency     fundamental frequency in Hz
     * @param sampleRate    sample rate in Hz
     * @param amplitudeVRms desired fundamental amplitude in V RMS
     * @param ampRatios     per-harmonic amplitude ratios (relative to fundamental)
     * @param phiInits      per-harmonic initial phases (radians, DAC output reference)
     * @param freqsHz       per-harmonic frequencies in Hz
     */
    public SignalGenerator(double frequency, int sampleRate, double amplitudeVRms,
                           double[] ampRatios, double[] phiInits, double[] freqsHz) {
        this(GenSignalForm.SINE_COMPENSATED, frequency, sampleRate, amplitudeVRms);
        int n = ampRatios.length;
        hAmpRatio = new double[n];
        hNum      = new int[n];
        hPhiInit  = new double[n];
        for (int i = 0; i < n; i++) {
            hAmpRatio[i] = ampRatios[i];
            hNum[i]      = (int) Math.round(freqsHz[i] / frequency);
            hPhiInit[i]  = phiInits[i];
            log.info("Accumulated H{}: {} Hz  {} dBFS  phi_init {} deg",
                    hNum[i],
                    String.format(Locale.US, "%.3f", freqsHz[i]),
                    String.format(Locale.US, "%.4f", 20.0 * Math.log10(ampRatios[i])),
                    String.format(Locale.US, "%.2f", Math.toDegrees(phiInits[i])));
        }
        log.info("Harmonic compensation: {} harmonic(s) from accumulated corrections", n);
    }

    /**
     * Constructs a {@link GenSignalForm#LINEAR_SWEEP} generator.  Generates a phase-continuous
     * linear (constant-rate) frequency sweep from {@code freqStart} → {@code freqEnd} over
     * {@code periodSamples} samples, then loops back to the start.  Looping keeps the DAC
     * fed for capture sessions longer than one sweep period.
     *
     * @param freqStart      sweep start frequency in Hz (instantaneous frequency at sample 0)
     * @param freqEnd        sweep end   frequency in Hz (instantaneous frequency at the last sample of the period)
     * @param sampleRate     sample rate in Hz
     * @param periodSamples  duration of one full sweep cycle in samples
     * @param amplitudeVRms  desired output amplitude in V RMS
     */
    public SignalGenerator(double freqStart, double freqEnd, int sampleRate,
                           int periodSamples, double amplitudeVRms) {
        this.form               = GenSignalForm.LINEAR_SWEEP;
        this.currentVrms        = amplitudeVRms;
        this.amplitude          = amplitudeVRms / (FS_VOLTAGE * rawRms(GenSignalForm.LINEAR_SWEEP));
        this.phaseInc           = 0;            // unused for sweep
        this.sampleRate         = sampleRate;
        this.sweepFreqStart     = freqStart;
        this.sweepFreqEnd       = freqEnd;
        this.sweepSampleRate    = sampleRate;
        this.sweepPeriodSamples = periodSamples;
        this.sweepIdx           = 0;
        this.sweepPhase         = 0.0;
        log.info("DDS sweep: f0={}Hz f1={}Hz period={} samples ({} s) amplitude={}V RMS",
                String.format(Locale.US, "%.4f", freqStart),
                String.format(Locale.US, "%.4f", freqEnd),
                periodSamples,
                String.format(Locale.US, "%.4f", periodSamples / (double) sampleRate),
                String.format(Locale.US, "%.6f", amplitudeVRms));
    }

    /**
     * Constructs a {@link GenSignalForm#LOG_SWEEP} generator: emits {@code leadInSamples}
     * samples of silence, then a Farina-style exponential sine sweep from {@code f0}
     * to {@code f1} over {@code sweepSamples} samples, then silence forever.
     *
     * <p>The sweep waveform is pre-rendered into an internal buffer so the analyzer
     * can take it back via {@link #getLogSweepBuffer()} and use it as the reference
     * X(t) for FFT-based deconvolution Y(f)/X(f) → H(f) (frequency response).
     *
     * @param f0             sweep start frequency in Hz (instantaneous frequency at sample 0)
     * @param f1             sweep end   frequency in Hz (instantaneous frequency at the last sweep sample)
     * @param sweepSamples   sweep duration in samples
     * @param leadInSamples  silent samples emitted before the sweep
     * @param sampleRate     sample rate in Hz
     * @param amplitudeVRms  sweep amplitude in V RMS
     */
    public SignalGenerator(double f0, double f1, int sweepSamples, int leadInSamples,
                           int sampleRate, double amplitudeVRms) {
        this.form           = GenSignalForm.LOG_SWEEP;
        this.currentVrms    = amplitudeVRms;
        this.amplitude      = amplitudeVRms / (FS_VOLTAGE * rawRms(GenSignalForm.LOG_SWEEP));
        this.phaseInc       = 0;            // unused for sweep
        this.sampleRate     = sampleRate;
        this.logSweepBuffer = renderLogSweep(f0, f1, sweepSamples, sampleRate);
        this.logSweepLeadIn = leadInSamples;
        this.logSweepIdx    = 0L;
        log.info("DDS log sweep: f0={}Hz f1={}Hz duration={} samples ({} s), lead-in {} samples ({} s), amplitude={}V RMS",
                String.format(Locale.US, "%.4f", f0),
                String.format(Locale.US, "%.4f", f1),
                sweepSamples,
                String.format(Locale.US, "%.4f", sweepSamples / (double) sampleRate),
                leadInSamples,
                String.format(Locale.US, "%.4f", leadInSamples / (double) sampleRate),
                String.format(Locale.US, "%.6f", amplitudeVRms));
    }

    /**
     * Renders a unit-amplitude (peak 1.0) Farina exponential sine sweep:
     * {@code x(t) = sin(K · (exp(t/L) − 1))} where {@code L = T/ln(f1/f0)} and
     * {@code K = 2π·f0·L}.  Instantaneous frequency advances log-linearly from
     * {@code f0} at t=0 to {@code f1} at t=T.  Phase starts at zero (sample 0 is
     * exactly 0) so the sweep can be concatenated with leading silence without a
     * discontinuity.
     *
     * <p>Both the player and the deconvolution analyzer call this so the reference
     * X(t) is byte-identical to what was sent to the DAC.
     */
    public float[] renderLogSweep(double f0, double f1, int sweepSamples, int sampleRate) {
        double T = sweepSamples / (double) sampleRate;
        double L = T / Math.log(f1 / f0);
        double K = 2.0 * Math.PI * f0 * L;
        float[] buf = new float[sweepSamples];
        for (int n = 0; n < sweepSamples; n++) {
            double t = n / (double) sampleRate;
            buf[n] = (float) Math.sin(K * (Math.exp(t / L) - 1.0));
        }
        return buf;
    }

    /** Returns the pre-rendered unit-amplitude log-sweep buffer (LOG_SWEEP only). */
    public float[] getLogSweepBuffer() { return logSweepBuffer; }

    /**
     * Resets the sweep playback position so the next {@link #nextSample()}
     * starts from the beginning of the lead-in (LOG_SWEEP) or the start of
     * the cycle (LINEAR_SWEEP).  Called by playback backends after any
     * pre-stream JIT warmup that consumed samples from this generator —
     * without this, a freq-response measurement would see the recorder
     * capture a sweep that started mid-buffer, and the deconvolution
     * reference would not align with the captured signal.
     */
    public void resetSweepPosition() {
        this.logSweepIdx = 0L;
        this.sweepIdx    = 0;
        this.sweepPhase  = 0.0;
        this.phaseAcc    = 0L;
    }

    /**
     * Returns the theoretical RMS value of the raw (unit-amplitude) signal for each waveform.
     * Used to convert a target V RMS into a linear peak amplitude scale factor.
     *
     * Deterministic waveforms: exact analytical values.
     * Noise waveforms: approximate, based on the Voss–McCartney structure (PINK_OCTAVES+1 summed terms).
     */
    private double rawRms(GenSignalForm form) {
        return switch (form) {
            case SINE, SINE_COMPENSATED   -> 1.0 / Math.sqrt(2.0);                       // sine RMS = peak / √2
            case LINEAR_SWEEP             -> 1.0 / Math.sqrt(2.0);                       // sweep is sin(φ(n)); RMS = peak / √2
            case LOG_SWEEP                -> 1.0 / Math.sqrt(2.0);                       // sweep is sin(φ(n)); RMS = peak / √2
            case TRIANGLE                 -> 1.0 / Math.sqrt(3.0);                       // triangle RMS = peak / √3 (independent of duty)
            case RECTANGLE                -> 1.0;                                         // ±peak square wave (any duty) → RMS = peak
            case WHITE_NOISE              -> 1.0;                                         // Gaussian std dev = 1
            case PINK_NOISE               -> 1.0 / Math.sqrt(PINK_OCTAVES + 1.0);        // Gaussian source, 17 summed terms / 17
            case PINK_NOISE_LINEAR        -> 1.0 / Math.sqrt(3.0 * (PINK_OCTAVES + 1.0));// uniform source, std = 1/√3 per term
            case DUAL_TONE                -> rawRmsDualTone();                            // depends on per-tone weights — see rawRmsDualTone
        };
    }

    /** RMS of the unscaled DUAL_TONE waveform for the CURRENT
     *  {@link #dualW1} / {@link #dualW2} weights.
     *
     *  <p>{@code raw = w₁·sin(ω₁t) + w₂·sin(ω₂t)} (uncorrelated sines at
     *  different frequencies), so {@code RMS² = (w₁² + w₂²) / 2} and
     *  {@code RMS = √((w₁² + w₂²) / 2)}.  Floored at a tiny positive
     *  value so the {@code amplitude = Vrms / (FS · rawRms)} divide
     *  doesn't go infinite when both weights are zero (which would mean
     *  the user dialled both tones to 0 % — silence, but we still need
     *  a finite amplitude scale to avoid NaN propagation). */
    private double rawRmsDualTone() {
        double rms2 = (dualW1 * dualW1 + dualW2 * dualW2) / 2.0;
        return Math.max(1e-12, Math.sqrt(rms2));
    }

    /** State-aware wrapper around {@link #rawRms(GenSignalForm)} —
     *  reads the current form from the field instead of taking it as
     *  a parameter.  Used by the dual-tone re-normalisation path
     *  where {@link #setDualToneAmplitudes} needs to recompute
     *  {@link #amplitude} against the new weights. */
    private double rawRmsForCurrentState() {
        return rawRms(form);
    }

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    /**
     * Live-swaps the waveform.  Phase accumulator is preserved so the
     * transition between phase-continuous forms (sine/saw/triangle) is
     * smooth.  Switching <em>to</em> {@link GenSignalForm#SINE_COMPENSATED}
     * without previously loading harmonics simply produces an uncorrected
     * sine — the per-harmonic correction arrays remain {@code null}.
     * Sweep forms expect their own constructor and shouldn't be reached
     * via this setter.
     */
    public void setForm(GenSignalForm newForm) {
        if (newForm == null || newForm == form) return;
        // Re-scale amplitude so the new form keeps the same V RMS output —
        // sine and triangle / saw / noise have different peak / RMS ratios.
        // {@link #currentVrms} is the cached "what the user dialled" and
        // gets re-divided against the new form's rawRms.
        this.form      = newForm;
        this.amplitude = currentVrms / (FS_VOLTAGE * rawRms(newForm));
    }

    /**
     * Live-updates the output frequency (Hz).  Phase accumulator is
     * preserved so the change is phase-continuous (no audible click).
     * Sweep forms ignore this — their instantaneous frequency is driven
     * by their own state machine.
     */
    public void setFrequency(double frequencyHz) {
        this.phaseInc = Math.round(frequencyHz / (double) sampleRate * 4294967296.0);
    }

    /** Live-updates the second tone's frequency for the
     *  {@link GenSignalForm#DUAL_TONE} waveform.  No-op for every other
     *  form (the second accumulator only advances when the form is
     *  DUAL_TONE).  Phase-continuous like {@link #setFrequency}. */
    public void setDualToneFrequency2(double frequencyHz) {
        this.phaseInc2 = Math.round(frequencyHz / (double) sampleRate * 4294967296.0);
    }

    /** Live-updates the dual-tone amplitude split.  {@code amp1Pct} +
     *  {@code amp2Pct} are interpreted as LINEAR amplitude percentages
     *  per tone (not power) — the per-tone DDS weight is the
     *  percentage divided by 100.  Each value is clamped to
     *  {@code [0, 100]} independently.
     *
     *  <p>After updating the weights the internal {@code amplitude}
     *  scale is re-normalised against the new
     *  {@code rawRms() = √((w₁² + w₂²) / 2)} so the combined signal's
     *  Vrms still matches whatever was last passed to
     *  {@link #setAmplitudeVrms}.  Without the re-normalisation a
     *  50/50 split would emit a noticeably quieter signal than a 100/0
     *  single-tone case at the same Amplitude-field setting. */
    public void setDualToneAmplitudes(double amp1Pct, double amp2Pct) {
        double a1 = Math.max(0.0, Math.min(100.0, amp1Pct)) / 100.0;
        double a2 = Math.max(0.0, Math.min(100.0, amp2Pct)) / 100.0;
        this.dualW1 = a1;
        this.dualW2 = a2;
        // Re-derive the amplitude scale from the cached Vrms so the
        // combined RMS stays equal to the Amplitude field's value
        // regardless of how the user splits the two tones.
        this.amplitude = currentVrms / (FS_VOLTAGE * rawRmsForCurrentState());
    }

    /**
     * Live-updates the output amplitude (V RMS).  Takes effect on the
     * next sample emitted; no audible click unless the change is large.
     */
    public void setAmplitudeVrms(double amplitudeVRms) {
        this.currentVrms = amplitudeVRms;
        this.amplitude   = amplitudeVRms / (FS_VOLTAGE * rawRms(form));
    }

    /**
     * Live-updates the rectangle waveform's duty cycle.  Clamped to
     * {@code [0.001, 0.999]} so the pulse train never collapses to a
     * constant DC level.  No-op for non-rectangle forms.
     */
    public void setRectangleDuty(double duty) {
        if (Double.isNaN(duty) || Double.isInfinite(duty)) return;
        if (duty < 0.001) duty = 0.001;
        if (duty > 0.999) duty = 0.999;
        this.rectDuty = duty;
    }

    /**
     * Live-updates the triangle waveform's duty cycle (rise-portion
     * fraction).  Clamped to {@code [0.001, 0.999]} so the rise or fall
     * segment never collapses to zero width (which would produce a step
     * discontinuity).  No-op for non-triangle forms.
     */
    public void setTriangleDuty(double duty) {
        if (Double.isNaN(duty) || Double.isInfinite(duty)) return;
        if (duty < 0.001) duty = 0.001;
        if (duty > 0.999) duty = 0.999;
        this.triDuty = duty;
    }

    /**
     * Returns the next sample in the range [-1.0, +1.0] scaled by amplitude.
     * Advances the phase accumulator by one step.
     */
    public double nextSample() {
        double raw = switch (form) {
            case SINE              -> ddsSine();
            case TRIANGLE          -> ddsTriangle();
            case RECTANGLE         -> ddsRectangle();
            case WHITE_NOISE       -> rng.nextGaussian();
            case PINK_NOISE        -> pinkNoise(false);
            case PINK_NOISE_LINEAR -> pinkNoise(true);
            case SINE_COMPENSATED  -> ddsSineCompensated();
            case LINEAR_SWEEP      -> linearSweepNext();
            case LOG_SWEEP         -> logSweepNext();
            case DUAL_TONE         -> ddsSine() * dualW1 + ddsSine2() * dualW2;
        };
        phaseAcc  = (phaseAcc  + phaseInc)  & 0xFFFFFFFFL;
        // Second accumulator only advances for DUAL_TONE.  Cheap branch
        // — the audio loop already executed the per-form switch and
        // form is volatile-cached locally by the JIT.
        if (form == GenSignalForm.DUAL_TONE) {
            phaseAcc2 = (phaseAcc2 + phaseInc2) & 0xFFFFFFFFL;
        }
        return raw * amplitude;
    }

    /**
     * Linear-sweep kernel: phase-continuous chirp whose instantaneous frequency
     * advances linearly from {@code sweepFreqStart} to {@code sweepFreqEnd}
     * across {@code sweepPeriodSamples} samples.  Loops back to the start when
     * {@link #sweepLoop} is true (phase-continuous restart so the DAC sees no
     * clicks); otherwise goes silent after one cycle.  Hann fade in/out
     * smooths the cycle edges if configured.
     */
    private double linearSweepNext() {
        if (sweepIdx >= sweepPeriodSamples) {
            if (!sweepLoop) return 0.0;
            sweepIdx   = 0;
            sweepPhase = 0.0;
        }
        double frac  = sweepIdx / (double) sweepPeriodSamples;
        double instF = sweepFreqStart + (sweepFreqEnd - sweepFreqStart) * frac;
        double s     = Math.sin(sweepPhase);
        sweepPhase  += 2.0 * Math.PI * instF / sweepSampleRate;
        // Wrap to keep phase magnitude bounded for double precision.
        if (sweepPhase >= 2.0 * Math.PI) {
            sweepPhase -= 2.0 * Math.PI * Math.floor(sweepPhase / (2.0 * Math.PI));
        }
        double env = sweepEnvelope(sweepIdx, sweepPeriodSamples);
        sweepIdx++;
        return s * env;
    }

    /**
     * Log-sweep kernel: emits {@code logSweepLeadIn} zeros, then replays the
     * pre-rendered {@code logSweepBuffer} sample-by-sample.  When
     * {@link #sweepLoop} is true the buffer is replayed back-to-back (without
     * re-emitting the lead-in silence); otherwise the output stays at zero
     * after the first cycle.  Hann fade in/out is applied per cycle.
     */
    private double logSweepNext() {
        long idx = logSweepIdx++;
        if (idx < logSweepLeadIn) return 0.0;
        long sIdx = idx - logSweepLeadIn;
        int bufLen = logSweepBuffer.length;
        if (sIdx >= bufLen) {
            if (!sweepLoop) return 0.0;
            // Wrap back to the start of the buffer (skip lead-in on
            // subsequent cycles).  logSweepIdx is at the next sample
            // after the just-emitted one — set it so the next call lands
            // at bufIdx = 0.
            long completed = (sIdx - 1) / bufLen + 1;
            logSweepIdx = logSweepLeadIn + (sIdx - completed * bufLen) + 1;
            sIdx = sIdx % bufLen;
        }
        int bufIdx = (int) sIdx;
        double env = sweepEnvelope(bufIdx, bufLen);
        return logSweepBuffer[bufIdx] * env;
    }

    /** Returns the Hann fade envelope value for sample {@code idx} within a
     *  cycle of length {@code cycleLength}.  Fade in covers the first
     *  {@link #fadeInSamples}; fade out covers the last {@link #fadeOutSamples}.
     *  Returns 1.0 in the steady-state middle of the cycle, or when the
     *  fade lengths are 0. */
    private double sweepEnvelope(int idx, int cycleLength) {
        int fIn = fadeInSamples;
        int fOut = fadeOutSamples;
        if (fIn > 0 && idx < fIn) {
            return 0.5 * (1.0 - Math.cos(Math.PI * idx / fIn));
        }
        if (fOut > 0 && idx >= cycleLength - fOut) {
            int back = cycleLength - 1 - idx;
            if (back < 0) back = 0;
            return 0.5 * (1.0 - Math.cos(Math.PI * back / fOut));
        }
        return 1.0;
    }

    /** Live-applies sweep loop and fade parameters; safe to call after
     *  construction.  Fade lengths are clamped to half the sweep cycle
     *  so the in-fade and out-fade can never overlap. */
    public void setSweepParams(boolean loop, int fadeInSamples, int fadeOutSamples) {
        this.sweepLoop = loop;
        int cycle = sweepCycleLength();
        int half = Math.max(0, cycle / 2);
        this.fadeInSamples  = Math.max(0, Math.min(fadeInSamples,  half));
        this.fadeOutSamples = Math.max(0, Math.min(fadeOutSamples, half));
    }

    /** Live-applies sweep start frequency (Hz).  Triggers LOG_SWEEP buffer
     *  regeneration since the pre-rendered buffer depends on it. */
    public void setSweepFreqStart(double hz) {
        if (!Double.isFinite(hz) || hz < 0) return;
        if (form == GenSignalForm.LINEAR_SWEEP) {
            sweepFreqStart = hz;
        } else if (form == GenSignalForm.LOG_SWEEP) {
            sweepFreqStart = hz;
            rebuildLogSweepBuffer();
        }
    }

    /** Live-applies sweep stop frequency (Hz). */
    public void setSweepFreqEnd(double hz) {
        if (!Double.isFinite(hz) || hz < 0) return;
        if (form == GenSignalForm.LINEAR_SWEEP) {
            sweepFreqEnd = hz;
        } else if (form == GenSignalForm.LOG_SWEEP) {
            sweepFreqEnd = hz;
            rebuildLogSweepBuffer();
        }
    }

    /** Live-applies sweep duration in samples.  For LINEAR_SWEEP just
     *  updates the period counter; for LOG_SWEEP rebuilds the pre-rendered
     *  buffer. */
    public void setSweepDurationSamples(int samples) {
        if (samples < 2) samples = 2;
        if (form == GenSignalForm.LINEAR_SWEEP) {
            sweepPeriodSamples = samples;
            if (sweepIdx >= sweepPeriodSamples) sweepIdx = 0;
            reclampFadeToCycle();
        } else if (form == GenSignalForm.LOG_SWEEP) {
            // Allocate a new buffer at the requested length so subsequent
            // logSweepNext() reads see the new size.  Position is reset
            // to the start of the buffer (skip lead-in) so the user
            // doesn't get stuck halfway through an outdated cycle.
            float[] fresh = renderLogSweep(sweepFreqStart, sweepFreqEnd, samples, sampleRate);
            this.logSweepBuffer = fresh;
            this.logSweepIdx    = logSweepLeadIn;
            reclampFadeToCycle();
        }
    }

    /** Re-renders the LOG_SWEEP buffer for the current start/stop/duration
     *  values.  Called after any of those change so the playback sample
     *  source actually reflects the new parameters. */
    private void rebuildLogSweepBuffer() {
        if (form != GenSignalForm.LOG_SWEEP) return;
        int len = (logSweepBuffer != null) ? logSweepBuffer.length : 0;
        if (len < 2) return;
        this.logSweepBuffer = renderLogSweep(sweepFreqStart, sweepFreqEnd, len, sampleRate);
        // Reset playback to the start of the new buffer so the user hears
        // the new sweep from the beginning instead of a discontinuity.
        this.logSweepIdx = logSweepLeadIn;
    }

    /** Returns the current sweep-cycle length in samples (period for
     *  LINEAR_SWEEP, buffer length for LOG_SWEEP, 0 for non-sweep forms). */
    private int sweepCycleLength() {
        if (form == GenSignalForm.LINEAR_SWEEP) return sweepPeriodSamples;
        if (form == GenSignalForm.LOG_SWEEP   ) return (logSweepBuffer != null) ? logSweepBuffer.length : 0;
        return 0;
    }

    /** Re-clamps the fade lengths to the new cycle length after a
     *  duration change.  Keeps the in-fade + out-fade from overlapping. */
    private void reclampFadeToCycle() {
        int cycle = sweepCycleLength();
        int half = Math.max(0, cycle / 2);
        if (fadeInSamples  > half) fadeInSamples  = half;
        if (fadeOutSamples > half) fadeOutSamples = half;
    }

    /** Live-applies sweep fade-in length (samples). */
    public void setSweepFadeInSamples(int samples) {
        int half = Math.max(0, sweepCycleLength() / 2);
        this.fadeInSamples = Math.max(0, Math.min(samples, half));
    }

    /** Live-applies sweep fade-out length (samples). */
    public void setSweepFadeOutSamples(int samples) {
        int half = Math.max(0, sweepCycleLength() / 2);
        this.fadeOutSamples = Math.max(0, Math.min(samples, half));
    }

    /** Live-applies the sweep loop flag. */
    public void setSweepLoop(boolean loop) {
        this.sweepLoop = loop;
    }

    // -------------------------------------------------------------------------
    // DDS waveform kernels
    // -------------------------------------------------------------------------

    /**
     * DDS sine with 9th-order Taylor series correction (Horner-evaluated).
     *
     * Phase accumulator → top 16 bits select the lookup table entry (coarse angle θ₀),
     * bottom 16 bits carry the fractional phase error Δθ (in radians, ≤ 9.6e-5).
     *   sin(θ₀ + Δθ) = sin(θ₀)·cos(Δθ) + cos(θ₀)·sin(Δθ)
     * with
     *   cos(Δθ) ≈ 1 − Δθ²/2 + Δθ⁴/24 − Δθ⁶/720 + Δθ⁸/40320
     *   sin(Δθ) ≈ Δθ − Δθ³/6 + Δθ⁵/120 − Δθ⁷/5040 + Δθ⁹/362880
     *
     * <p>At TABLE_BITS=16 the Δθ ≤ 9.6e-5 rad bound makes order-5 truncation
     * already accurate to ~6.8e-23 (≈ −400 dB) — well below double-precision ε.
     * The order-9 form here is overkill for the current table size but costs
     * only a few flops and removes the Taylor correction from the error budget
     * if TABLE_BITS is ever reduced to shrink the lookup table.
     */
    private double ddsSine() {
        int    idx  = (int) (phaseAcc >>> (32 - TABLE_BITS));   // 0 .. 65535
        long   frac = phaseAcc & ((1L << (32 - TABLE_BITS)) - 1);
        double dx   = frac * TWO_PI_OVER_2_32;                  // fractional radians
        double dx2  = dx * dx;
        double cosDx = 1.0 + dx2 * (-0.5
                              + dx2 * (1.0 / 24.0
                              + dx2 * (-1.0 / 720.0
                              + dx2 * (1.0 / 40320.0))));
        double sinDx = dx * (1.0 + dx2 * (-1.0 / 6.0
                                  + dx2 * (1.0 / 120.0
                                  + dx2 * (-1.0 / 5040.0
                                  + dx2 * (1.0 / 362880.0)))));
        double sinT = SINE_TABLE[idx];
        double cosT = COS_TABLE[idx];
        return sinT * cosDx + cosT * sinDx;
    }

    /** Second DDS sine reader — identical math to {@link #ddsSine}, but
     *  reads {@link #phaseAcc2} instead of {@link #phaseAcc} so the
     *  dual-tone waveform can run two independent oscillators in lock-
     *  step with a single sample tick.  Kept as a separate method
     *  rather than parameterising {@code ddsSine} so the JIT can still
     *  inline the per-tone read without an extra parameter copy. */
    private double ddsSine2() {
        int    idx  = (int) (phaseAcc2 >>> (32 - TABLE_BITS));
        long   frac = phaseAcc2 & ((1L << (32 - TABLE_BITS)) - 1);
        double dx   = frac * TWO_PI_OVER_2_32;
        double dx2  = dx * dx;
        double cosDx = 1.0 + dx2 * (-0.5
                              + dx2 * (1.0 / 24.0
                              + dx2 * (-1.0 / 720.0
                              + dx2 * (1.0 / 40320.0))));
        double sinDx = dx * (1.0 + dx2 * (-1.0 / 6.0
                                  + dx2 * (1.0 / 120.0
                                  + dx2 * (-1.0 / 5040.0
                                  + dx2 * (1.0 / 362880.0)))));
        double sinT = SINE_TABLE[idx];
        double cosT = COS_TABLE[idx];
        return sinT * cosDx + cosT * sinDx;
    }

    /**
     * DDS rectangle / pulse train.  Output is {@code +1} for the first
     * {@link #rectDuty} fraction of the period, {@code −1} for the rest.
     * A 50 % duty cycle produces a symmetric square wave; other duty values
     * have a non-zero DC component which is the user's intent for pulse-
     * style test signals.
     */
    private double ddsRectangle() {
        double frac = (phaseAcc & 0xFFFFFFFFL) * (1.0 / 4294967296.0);   // [0, 1)
        return frac < rectDuty ? +1.0 : -1.0;
    }

    /**
     * DDS triangle with adjustable duty cycle.  The rising portion takes
     * {@link #triDuty} of the period (−1 → +1), the falling portion takes
     * the remainder (+1 → −1).  At {@code triDuty = 0.5} the waveform is a
     * symmetric triangle; near {@code 1.0} it approaches a sawtooth; near
     * {@code 0.0} it approaches an inverted sawtooth.  Piecewise-linear in
     * the phase domain — exact by construction.
     */
    private double ddsTriangle() {
        double frac = (phaseAcc & 0xFFFFFFFFL) * (1.0 / 4294967296.0);   // [0, 1)
        double d = triDuty;
        if (frac < d) {
            return frac / d * 2.0 - 1.0;
        } else {
            return 1.0 - (frac - d) / (1.0 - d) * 2.0;
        }
    }

    // -------------------------------------------------------------------------
    // Noise generators
    // -------------------------------------------------------------------------

    /**
     * Pink noise via the Voss–McCartney summed-octave algorithm.
     *
     * @param linear true  → uniformly distributed white source (flat amplitude PDF)
     *               false → Gaussian white source
     */
    private double pinkNoise(boolean linear) {
        pinkCounter++;
        int trailing = Long.numberOfTrailingZeros(pinkCounter);
        if (trailing < PINK_OCTAVES) {
            double newVal = linear ? (rng.nextDouble() * 2.0 - 1.0) : rng.nextGaussian();
            pinkRunningSum += newVal - pinkRows[trailing];
            pinkRows[trailing] = newVal;
        }
        double white = linear ? (rng.nextDouble() * 2.0 - 1.0) : rng.nextGaussian();
        return (pinkRunningSum + white) / (PINK_OCTAVES + 1.0);
    }

    // -------------------------------------------------------------------------
    // Harmonic compensation
    // -------------------------------------------------------------------------

    /**
     * Initialises harmonic compensation phasors directly from a {@link FftResult}.
     * Equivalent to {@link #loadHarmonics} but avoids writing a CSV file.
     * Only harmonics whose bin index is valid (> 0) are loaded.
     */
    private void loadHarmonicsFromResult(double frequency, int sampleRate, FftResult r) {
        if (!r.coherentAveraging) {
            log.warn("FFT result uses incoherent averaging — phase information unavailable; "
                   + "phase correction disabled, amplitude correction only.");
        }

        // Fundamental phase: atan2(im, re) at the fundamental bin.
        // For incoherent results im[k] = 0, so phi1 = 0 → omegaD = -π/2 (no real correction).
        double phi1   = Math.atan2(r.im[r.fundamentalBin], r.re[r.fundamentalBin]);
        double omegaD = -(phi1 + Math.PI / 2.0);
        // Convert delay to rad/Hz so each harmonic uses its own actual frequency
        double delayRadPerHz = omegaD / r.fundamentalHzRefined;
        log.info("System delay estimate: {} rad ({} samples at {} Hz)",
                String.format(Locale.US, "%.2f", omegaD),
                String.format(Locale.US, "%.4f", omegaD / (2.0 * Math.PI * frequency / sampleRate)),
                (double) sampleRate);

        // Collect valid harmonics (H2 .. Hn)
        int validCount = 0;
        for (int h = 0; h < r.harmonicCount; h++) {
            if (r.harmonicBins[h] > 0) validCount++;
        }

        hAmpRatio = new double[validCount];
        hNum      = new int[validCount];
        hPhiInit  = new double[validCount];

        int i = 0;
        for (int h = 0; h < r.harmonicCount; h++) {
            int bin = r.harmonicBins[h];
            if (bin <= 0) continue;

            double phiH     = Math.atan2(r.im[bin], r.re[bin]);
            double ampRatio = r.harmonicPct[h] / 100.0;
            double freqHz   = r.harmonicHz[h];
            int    hNumber  = h + 2;

            double phiInit = phiH + freqHz * delayRadPerHz;
            hAmpRatio[i]   = ampRatio;
            hNum[i]        = hNumber;
            hPhiInit[i]    = phiInit;
            log.info("Harmonic compensation H{}: {} Hz  {} dBFS  phi_meas {} deg  phi_init {} deg",
                    hNumber,
                    String.format(Locale.US, "%.3f", freqHz),
                    String.format(Locale.US, "%.4f", 20.0 * Math.log10(ampRatio)),
                    String.format(Locale.US, "%.2f", Math.toDegrees(phiH)),
                    String.format(Locale.US, "%.2f", Math.toDegrees(phiInit)));
            i++;
        }
        log.info("Harmonic compensation: {} harmonic(s) loaded from FFT result", validCount);
    }

    /**
     * Parses an {@code fft_harmonics_*.csv} file and initialises the per-harmonic
     * rotating phasors for {@link GenSignalForm#SINE_COMPENSATED}.
     * Skips H1 (fundamental). For each H2..Hn entry the phasor is initialised from
     * the {@code re}/{@code im} columns when present (full double precision), otherwise
     * from {@code phase_deg}.  The correction amplitude is taken from
     * {@code amplitude_pct / 100} so it is automatically relative to the fundamental
     * regardless of the absolute DAC/ADC level.
     */
    private void loadHarmonics(double frequency, int sampleRate,
                                String csvPath) throws IOException {
        // [ampRatio, phi_measured (rad), freqHz, harmonicNumber]
        List<double[]> list = new ArrayList<>();
        double phi1 = Double.NaN;   // fundamental measured phase (rad) — used for delay compensation

        try (BufferedReader br = new BufferedReader(new FileReader(csvPath))) {
            String line;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                // skip blank lines, comments, and the header row
                if (line.isEmpty() || !Character.isDigit(line.charAt(0))) continue;
                String[] cols = line.split(";");
                if (cols.length < 5) continue;
                int hIndex = Integer.parseInt(cols[0].trim());

                // Derive phase from re/im (full precision) or phase_deg column
                double phi;
                if (cols.length >= 7) {
                    double re  = Double.parseDouble(cols[5].trim().replace(',', '.'));
                    double im  = Double.parseDouble(cols[6].trim().replace(',', '.'));
                    phi = Math.atan2(im, re);
                } else {
                    phi = Math.toRadians(Double.parseDouble(cols[4].trim().replace(',', '.')));
                }

                if (hIndex == 1) {
                    phi1 = phi;   // capture fundamental phase for delay compensation
                    continue;
                }
                double ampPct = Double.parseDouble(cols[3].trim().replace(',', '.'));
                double freqHz = Double.parseDouble(cols[1].trim().replace(',', '.'));
                list.add(new double[]{ ampPct / 100.0, phi, freqHz, hIndex });
            }
        }

        if (Double.isNaN(phi1)) {
            // H1 row absent — assume DDS sine start phase (-π/2), delay unknown → no correction
            log.warn("H1 row not found in harmonics CSV — system-delay phase correction disabled");
            phi1 = -Math.PI / 2.0;
        }

        // System delay compensation:
        //   DDS sine at n=0 has FFT phase -π/2  →  phi1_measured = -ωD - π/2
        //   ωD = -(phi1_measured + π/2)
        //
        // For harmonic h the correction must arrive at the ADC with phase phi_h_measured.
        // It is sent from the DAC at phase phi_init and arrives delayed by h·ωD:
        //   phi_init - h·ωD = phi_h_measured
        //   phi_init = phi_h_measured + h·ωD = phi_h_measured - h·(phi1 + π/2)
        double omegaD = -(phi1 + Math.PI / 2.0);   // ωD in radians at fundamental
        double delayRadPerHz = omegaD / frequency;    // per-harmonic delay
        log.info("System delay estimate: {} rad ({} samples at {} Hz)",
                String.format(Locale.US, "%.2f", omegaD),
                String.format(Locale.US, "%.4f", omegaD / (2.0 * Math.PI * frequency / sampleRate)),
                (double) sampleRate);

        int n     = list.size();
        hAmpRatio = new double[n];
        hNum      = new int[n];
        hPhiInit  = new double[n];
        for (int i = 0; i < n; i++) {
            double[] h    = list.get(i);
            hAmpRatio[i]  = h[0];
            double phiH   = h[1];
            double freqHz = h[2];
            int    hNumber = (int) h[3];   // harmonic number: 2, 3, 4, …

            double phiInit = phiH + freqHz * delayRadPerHz;
            hNum[i]        = hNumber;
            hPhiInit[i]    = phiInit;
            log.info("Harmonic compensation H{}: {} Hz  {} dBFS  phi_meas {} deg  phi_init {} deg",
                    hNumber,
                    String.format(Locale.US, "%.3f", freqHz),
                    String.format(Locale.US, "%.4f", 20.0 * Math.log10(h[0])),
                    String.format(Locale.US, "%.2f", Math.toDegrees(phiH)),
                    String.format(Locale.US, "%.2f", Math.toDegrees(phiInit)));
        }
        log.info("Harmonic compensation: {} harmonic(s) loaded from {}", n, csvPath);
    }

    /**
     * DDS sine with H2..Hn harmonic compensation.
     *
     * Each harmonic's phase is derived by integer-multiplying the master 32-bit
     * phase accumulator by the harmonic number.  This locks the compensation
     * frequency exactly to h·f_DDS — no drift, no beating against the real
     * distortion harmonics, regardless of how many samples have been generated.
     */
    private double ddsSineCompensated() {
        double s = ddsSine();
        if (hAmpRatio != null) {
            for (int i = 0; i < hAmpRatio.length; i++) {
                long hPhase  = (phaseAcc * hNum[i]) & 0xFFFFFFFFL;
                double angle = hPhase * TWO_PI_OVER_2_32 + hPhiInit[i];
                s -= hAmpRatio[i] * Math.cos(angle);
            }
        }
        return s;
    }

    // -------------------------------------------------------------------------
    // Applied-compensation CSV metadata
    // -------------------------------------------------------------------------

    /**
     * Generator parameters recorded in the header of an
     * {@code applied_compensation_*.csv} file.  Any field is −1 / NaN when the
     * corresponding {@code #} metadata line was not present in the CSV.
     */
    @Value
    public static class Metadata {
        int    sampleRateHz;    // −1 if absent
        int    bitDepth;        // −1 if absent
        double amplitudeVRms;   //  0 if absent
        double frequencyHz;     //  0 if absent
    }

    /**
     * Parses generator-parameter metadata from {@code #}-prefixed comment lines
     * at the top of an {@code applied_compensation_*.csv} file.  Returns
     * {@code null} if no metadata line is found (e.g. legacy harmonics CSV).
     */
    public static Metadata readAppliedCompensationMetadata(String csvPath) throws IOException {
        int    sampleRate = -1;
        int    bitDepth   = -1;
        double amp        = 0.0;
        double freq       = 0.0;
        boolean any       = false;
        try (BufferedReader br = new BufferedReader(new FileReader(csvPath))) {
            String line;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty())      continue;
                if (!line.startsWith("#")) break;   // stop at first non-comment line
                String body = line.substring(1).trim();
                int eq = body.indexOf('=');
                if (eq <= 0) continue;
                String key = body.substring(0, eq).trim();
                String val = body.substring(eq + 1).trim();
                try {
                    switch (key) {
                        case "sample_rate_hz" -> { sampleRate = Integer.parseInt(val);    any = true; }
                        case "bit_depth"      -> { bitDepth   = Integer.parseInt(val);    any = true; }
                        case "amplitude_vrms" -> { amp        = Double.parseDouble(val);  any = true; }
                        case "frequency_hz"   -> { freq       = Double.parseDouble(val);  any = true; }
                        default -> { /* ignore unknown keys */ }
                    }
                } catch (NumberFormatException ignored) { /* skip malformed */ }
            }
        }
        return any ? new Metadata(sampleRate, bitDepth, amp, freq) : null;
    }
}
